trelloproject:
  key: 89b04a6238e8705a5fad7a5a3462a2f8
  token: dbb7b0bef8bf41638301238d4702d28a3bc23fe79605e2775cbd1af3806243a4
  base: https://api.trello.com/1

spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/trelloproject?useSSL=false&timeZone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

server:
  port: 8080
